---
- name: Converge
  hosts: all

  vars:
    burpsuite_user: hacker
    burpsuite_edition: community
    burpsuite_version: '2021.12'
    burpsuite_installer_sha256_checksum: a4c0c57686c9d509d66d8a131e7fae8ef259ef7650166e764854e47f41fac34a

  pre_tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ burpsuite_user }}"
        shell: /bin/bash
        create_home: true

  roles:
    - iesplin.burp_suite
