---
- name: Converge
  hosts: all

  vars:
    burpsuite_user: hacker
    burpsuite_edition: community
    burpsuite_release_channel: stable

  pre_tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ burpsuite_user }}"
        shell: /bin/bash
        create_home: true

  roles:
    - iesplin.burp_suite
