# code: language=ansible

---
- name: Set up a kali instance
  hosts: kalis
  vars:
    burpsuite_user: "vnc"
    burpsuite_edition: "pro"
    burpsuite_version: "latest"
    burpsuite_release_channel: "stable"
    burpsuite_activate: true
  vars_prompt:
    - name: burpsuite_pro_license_key
      prompt: "Please paste your Burp Suite Pro license key (base64 string)"
      private: false
  roles:
    - "common"
    - "kali"
      # - "firefox"
    - "burpsuite"
