---
- name: Set up a kali instance
  hosts: kalis
  vars:
    burpsuite_user: vnc
    burpsuite_edition: pro
    burpsuite_pro_license_key: PLACE_HOLDER
  roles:
    - "roles/common"
    - "roles/kali"
      #- "roles/firefox"
      #- "roles/burpsuite"
