# code: language=ansible

---
- name: Download and install BApp extension
  block:
    - name: Download BApp file
      ansible.builtin.get_url:
        url: "{{ item.value.bapp_link }}"
        dest: "{{ extension_dir }}/{{ item.key }}.bapp"
        mode: "0755"

    - name: Create installation directory
      ansible.builtin.file:
        path: "{{ extension_dir }}/{{ item.key }}"
        state: directory
        mode: "0755"

    - name: Unarchive BApp file
      ansible.builtin.unarchive:
        src: "{{ extension_dir }}/{{ item.key }}.bapp"
        dest: "{{ extension_dir }}/{{ item.key }}"

    - name: Clean up downloaded file
      ansible.builtin.file:
        state: absent
        path: "{{ extension_dir }}/{{ item.key }}.bapp"
