---
- name: Prepare /opt
  tags: git
  block:
    - name: Set mode for /opt
      ansible.builtin.file:
        path: /opt
        mode: "0755"
      become: true
      become_method: ansible.builtin.sudo
    - name: Mark /opt as safe within git
      ansible.builtin.blockinfile:
        path: /home/vnc/.gitconfig
        mode: "0644"
        block: |
          [safe]
            directory = /opt/*
        marker_begin: ANSIBLE_SAFE_OPT
        create: true

- name: Install kiterunner
  tags:
    - external-pkgs
    - kiterunner
  block:
    - name: Clone kiterunner repo
      ansible.builtin.git:
        repo: https://github.com/assetnote/kiterunner.git # noqa: latest
        dest: /opt/kiterunner
      become: true
      become_method: ansible.builtin.sudo

    - name: Build Kiterunner
      make:
        chdir: /opt/kiterunner
      become: true
      become_method: ansible.builtin.sudo

    - name: Create Kiterunner symlink
      ansible.builtin.file:
        src: /opt/kiterunner/dist/kr
        dest: /usr/local/bin/kr
        state: link
      become: true
      become_method: ansible.builtin.sudo

- name: Clone nuclei templates
  tags: nuclei-templates
  ansible.builtin.git:
    repo: https://github.com/projectdiscovery/nuclei-templates # noqa: latest
    dest: /opt/nuclei-templates
  become: true
  become_method: ansible.builtin.sudo
