---
# Include tasks

- name: Perform full-upgrade and install additional packages using apt
  ansible.builtin.include_tasks: apt.yml

- name: Install rust packages using cargo
  ansible.builtin.include_tasks: cargo.yml

- name: Install additional tools using git
  ansible.builtin.include_tasks: git.yaml

- name: Install go packages
  ansible.builtin.include_tasks: golang.yaml

- name: Install python packages using pip
  ansible.builtin.include_tasks: python.yaml

- name: Set up the EFS fileshare
  ansible.builtin.include_tasks: setup-share.yaml
