---
# Include tasks

- name: Perform full-upgrade and install additional packages using apt
  ansible.builtin.include_tasks: "roles/kali/tasks/apt.yaml"

- name: Install rust packages using cargo
  ansible.builtin.include_tasks: "roles/kali/tasks/cargo.yaml"

- name: Install additional tools using git
  ansible.builtin.include_tasks: "roles/kali/tasks/git.yaml"

- name: Install go packages
  ansible.builtin.include_tasks: "roles/kali/tasks/golang.yaml"

- name: Install python packages using pip
  ansible.builtin.include_tasks: "roles/kali/tasks/python.yaml"
