---
- name: Prepare /opt
  tags: git
  block:
    - name: Set mode for /opt
      ansible.builtin.file:
        path: /opt
        mode: '755'
      become: true
      become_method: ansible.builtin.sudo
    - name: Mark /opt as safe within git
      ansible.builtin.blockinfile:
        path: /home/vnc/.gitconfig
        mode: '644'
        block: |
          [safe]
            directory = /opt/*
        marker_begin: ANSIBLE_SAFE_OPT
        create: true

- name: Install github-search
  tags: github-search
  block:
    - name: Clone github-search repo
      ansible.builtin.git:
        repo: https://github.com/gwen001/github-search # noqa: latest
        dest: /opt/github-search
      become: true
      become_method: ansible.builtin.sudo
    - name: Install github-search requirements
      ansible.builtin.pip:
        requirements: /opt/github-search/requirements.txt
        virtualenv: /opt/github-search/venv

- name: Install python packages
  tags: external-pkgs
  block:
    - name: Install jmespath # requirement for burpsuite setup
      tags: jmespath
      ansible.builtin.pip:
        name: jmespath

    - name: Install arjun
      tags: arjun
      ansible.builtin.pip:
        name: arjun

    - name: Install subscraper
      tags: subscraper
      ansible.builtin.pip:
        name: git+https://github.com/m8sec/subscraper

    - name: Install xnLinkFinder.py
      tags: xnlinkfinder
      block:
        - name: Install xnLinkFinder.py with pip+git
          ansible.builtin.pip:
            name: git+https://github.com/xnl-h4ck3r/xnLinkFinder
        - name: Configure xnLinkFinder.py
          ansible.builtin.file:
            src: /home/vnc/.local/lib/python3.11/site-packages/xnLinkFinder.py
            dest: /home/vnc/.local/bin/xnLinkFinder.py
            mode: '755'
            state: link
